name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-10"

# compatibility_flags = [ "nodejs_compat" ]
[vars]
DATABASE_URL = "postgres://neondb_owner@*****ep-wild-leaf-a590nr6f.us-east-2.aws.neon.tech/neondb"
JWT_SECERT = "somasankar33secret"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1